kind: pipeline
type: docker
name: default

steps:
  # Build Backend Docker Image
  - name: build-backend
    image: plugins/docker
    settings:
      repo: registry.local.nothaft.cloud/picpeak-backend
      tags: 
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
        - ${DRONE_BRANCH}-latest
      dockerfile: backend/Dockerfile
      context: backend/
      registry: registry.local.nothaft.cloud
      build_args:
        - VERSION=${DRONE_TAG:-dev}
      
  # Build Frontend Docker Image
  - name: build-frontend
    image: plugins/docker
    settings:
      repo: registry.local.nothaft.cloud/picpeak-frontend
      tags: 
        - latest
        - ${DRONE_COMMIT_SHA:0:8}
        - ${DRONE_BRANCH}-latest
      dockerfile: frontend/Dockerfile
      context: frontend/
      registry: registry.local.nothaft.cloud
      build_args:
        - VERSION=${DRONE_TAG:-dev}
        - VITE_API_URL=${VITE_API_URL:-/api}

trigger:
  branch:
    - main
    - develop
  event:
    - push
    - pull_request

---
kind: pipeline
type: docker
name: release

steps:
  # Build Backend Release
  - name: build-backend-release
    image: plugins/docker
    settings:
      repo: registry.local.nothaft.cloud/picpeak-backend
      tags:
        - ${DRONE_TAG}
        - latest
      dockerfile: backend/Dockerfile
      context: backend/
      registry: registry.local.nothaft.cloud
      
  # Build Frontend Release
  - name: build-frontend-release
    image: plugins/docker
    settings:
      repo: registry.local.nothaft.cloud/picpeak-frontend
      tags:
        - ${DRONE_TAG}
        - latest
      dockerfile: frontend/Dockerfile
      context: frontend/
      registry: registry.local.nothaft.cloud

  # -------- NEW: Publish Docker images to GitHub Container Registry --------
  - name: push-backend-ghcr
    image: plugins/docker
    settings:
      repo: ghcr.io/the-luap/picpeak-backend
      tags:
        - ${DRONE_TAG}
        - latest
      dockerfile: backend/Dockerfile
      context: backend/
      registry: ghcr.io
      username:
        from_secret: GITHUB_USERNAME
      password:
        from_secret: GITHUB_TOKEN
      build_args:
        - VERSION=${DRONE_TAG}

  - name: push-frontend-ghcr
    image: plugins/docker
    settings:
      repo: ghcr.io/the-luap/picpeak-frontend
      tags:
        - ${DRONE_TAG}
        - latest
      dockerfile: frontend/Dockerfile
      context: frontend/
      registry: ghcr.io
      username:
        from_secret: GITHUB_USERNAME
      password:
        from_secret: GITHUB_TOKEN
      build_args:
        - VERSION=${DRONE_TAG}
        - VITE_API_URL=${VITE_API_URL:-/api}


trigger:
  event:
    - tag